export const chatTheme = {
  pageShell: 'min-h-screen bg-gradient-to-b from-[#2946a3] via-[#2947ad] to-[#22388f] text-white',
  appFrame: 'w-full max-w-[1440px] mx-auto h-screen flex',
  workspace: 'min-w-0 flex-1 h-screen flex flex-col',
  historyRail: 'hidden md:flex w-72 shrink-0 flex-col border-r border-white/10 bg-[#18264f]/72 px-3 py-4 backdrop-blur-md',
  historyHeader: 'flex flex-col gap-3 border-b border-white/10 pb-3',
  newSessionButton: 'h-10 w-full justify-center rounded-xl bg-white/10 px-3 text-sm font-medium text-white hover:bg-white/16 focus:outline-none focus:ring-2 focus:ring-white/25 transition-colors flex items-center gap-2',
  historyList: 'chat-scrollbar mt-3 flex-1 space-y-1.5 overflow-y-auto pr-1',
  historyItem: 'w-full rounded-xl border border-transparent px-3 py-2.5 text-left text-white/78 hover:border-white/12 hover:bg-white/9 transition-colors flex flex-col gap-1',
  historyItemActive: 'bg-[#f2b84b]/18 border-[#f2b84b]/28 text-white shadow-[0_10px_22px_rgba(10,18,48,0.16)]',
  historyItemTitle: 'truncate text-[13px] font-medium leading-5',
  historyItemMeta: 'text-[11px] text-white/48',
  historyState: 'flex min-h-12 items-center gap-2 rounded-xl border border-white/10 bg-white/6 px-3 text-xs text-white/62',
  historyError: 'mt-3 rounded-xl border border-red-300/18 bg-red-500/12 px-3 py-2 text-xs leading-5 text-red-100',
  header: 'bg-transparent px-6 lg:px-10 py-4 flex items-start justify-between gap-4 border-b border-white/8',
  brandIcon: 'w-5 h-10 bg-gradient-to-b from-[#48c6ff] to-[#3f7fff] rounded-full flex items-center justify-center shadow-[0_10px_24px_rgba(26,57,163,0.32)]',
  title: 'text-[18px] font-bold text-white tracking-tight',
  disclaimerToggle: 'h-8 px-3 rounded-full border border-white/12 bg-white/7 text-white/76 hover:bg-white/12 hover:text-white focus:outline-none focus:ring-2 focus:ring-white/25 transition-colors text-xs font-medium flex items-center gap-1.5',
  disclaimerText: 'mt-2 text-[11px] text-white/76 leading-[1.55] max-w-[980px]',
  statusText: 'text-[13px] text-white/85 font-medium',
  contentArea: 'chat-scrollbar flex-1 overflow-y-auto px-6 lg:px-10 pt-5 pb-44',
  emptyIconWrap: '',
  emptyIcon: '',
  starterSection: 'w-full max-w-[1180px] mx-auto text-left',
  starterToggle: 'w-full min-h-12 px-4 rounded-xl border border-white/12 bg-white/8 text-white hover:bg-white/12 focus:outline-none focus:ring-2 focus:ring-white/25 transition-colors flex items-center justify-between gap-3 text-sm font-medium',
  starterGrid: 'mt-3 grid grid-cols-1 xl:grid-cols-2 gap-3 overflow-hidden',
  starterCard: 'bg-[#2f416d]/74 rounded-xl px-4 py-4 border border-white/10 shadow-[0_14px_28px_rgba(17,28,73,0.16)] cursor-pointer transition-colors hover:bg-[#3a4d7b] hover:border-white/15',
  starterCardTitle: 'font-semibold text-white text-[15px] leading-6 mb-3 flex items-start gap-3',
  starterCardIndex: 'w-7 h-7 shrink-0 bg-[#4488ff] text-white rounded-full flex items-center justify-center text-sm font-semibold shadow-[0_8px_18px_rgba(33,97,255,0.35)]',
  starterCardPrompt: 'bg-[#24324b]/72 rounded-lg px-3 py-3 text-[14px] leading-6 text-[#edf3ff] border border-black/10',
  userBubble: 'bg-gradient-to-r from-[#4b76ff] to-[#4c46d9] text-white',
  assistantBubble: 'bg-[#24324b]/92 border border-white/10 text-[#edf3ff] shadow-[0_14px_28px_rgba(11,20,55,0.2)]',
  attachmentButton: 'mt-3 flex items-center gap-2 px-3 py-2 bg-[#4a7fff]/15 text-[#c9dcff] border border-[#79a4ff]/20 rounded-lg hover:bg-[#4a7fff]/20 transition-colors text-xs font-medium',
  assistantTimestamp: 'text-white/45',
  loadingBubble: 'bg-[#24324b]/92 rounded-2xl px-5 py-4 shadow-[0_14px_28px_rgba(11,20,55,0.2)] border border-white/10',
  loadingText: 'text-sm text-white/60',
  inputShell: 'sticky bottom-0 z-20 bg-transparent px-6 lg:px-10 py-4',
  inputInner: 'mx-auto flex w-full max-w-[1180px] flex-col gap-3',
  streamLabel: 'text-xs text-white/62 font-medium',
  streamButtonActive: 'bg-[#4488ff] text-white shadow-[0_8px_16px_rgba(31,88,255,0.28)]',
  streamButtonIdle: 'bg-white/10 border border-white/10 text-white/78 hover:bg-white/16 transition-colors',
  textarea: 'w-full px-4 py-4 pr-12 bg-[#eef4ff]/92 border border-white/20 rounded-2xl resize-none focus:outline-none focus:ring-2 focus:ring-[#9fc4ff]/45 text-black placeholder:text-black/55 shadow-[0_18px_40px_rgba(10,18,48,0.18)]',
  primaryButton: 'h-14 min-w-[104px] justify-center px-5 bg-gradient-to-br from-[#4b6fff] to-[#4b3ed0] text-white rounded-full font-medium flex items-center gap-2 hover:from-[#5880ff] hover:to-[#5748df] disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-[0_16px_28px_rgba(35,46,139,0.34)]',
  downloadButton: 'px-4 py-2 bg-gradient-to-r from-[#4b76ff] to-[#4c46d9] text-white rounded-xl text-sm font-medium flex items-center gap-2 hover:from-[#5880ff] hover:to-[#5a4fe5] transition-all',
  clearButton: 'p-2 text-white/60 hover:text-red-400 transition-colors',
  backButton: 'p-2 text-white/60 hover:text-white transition-colors',
  settingsButton: 'p-2 text-white/70 hover:text-white hover:bg-white/10 focus:outline-none focus:ring-2 focus:ring-white/25 rounded-full transition-colors',
  settingsMenu: 'absolute right-0 top-full mt-2 w-40 rounded-xl border border-white/12 bg-[#1f2f60]/96 p-1.5 shadow-[0_18px_42px_rgba(8,15,42,0.32)] backdrop-blur-md z-30',
  settingsMenuItem: 'w-full px-3 py-2 rounded-lg text-left text-sm text-white/84 hover:bg-white/10 hover:text-white transition-colors flex items-center gap-2',
  settingsMenuItemDanger: 'w-full px-3 py-2 rounded-lg text-left text-sm text-red-100 hover:bg-red-500/18 hover:text-white transition-colors flex items-center gap-2',
} as const;
