export const chatTheme = {
  pageShell: 'min-h-screen bg-gradient-to-br from-slate-950 via-slate-900 to-blue-950 text-white',
  workspace: 'max-w-4xl mx-auto h-screen flex flex-col',
  header: 'bg-white/10 backdrop-blur-md border-b border-white/10 px-6 py-4 flex items-center justify-between',
  brandIcon: 'w-10 h-10 bg-gradient-to-br from-cyan-400 to-blue-500 rounded-xl flex items-center justify-center shadow-lg shadow-cyan-950/40',
  title: 'text-lg font-semibold text-white',
  subtitle: 'text-xs text-white/60',
  statusText: 'text-xs text-white/60',
  contentArea: 'flex-1 overflow-y-auto p-6 space-y-4',
  emptyIconWrap: 'w-20 h-20 bg-white/10 border border-white/10 rounded-2xl flex items-center justify-center mx-auto mb-6 shadow-lg shadow-slate-950/30',
  emptyIcon: 'w-10 h-10 text-cyan-300',
  starterGrid: 'max-w-3xl mx-auto space-y-4 text-left',
  starterCard: 'bg-slate-950/70 rounded-2xl p-4 border border-white/10 shadow-lg shadow-slate-950/35 cursor-pointer hover:border-cyan-400/45 hover:bg-slate-900/85 transition-all',
  starterCardTitle: 'font-semibold text-white mb-3 flex items-start gap-2',
  starterCardIndex: 'w-6 h-6 shrink-0 bg-gradient-to-br from-cyan-400 to-blue-500 text-white rounded-full flex items-center justify-center text-xs shadow-md shadow-cyan-950/40',
  starterCardPrompt: 'bg-slate-900/80 border border-white/5 rounded-xl p-3 text-sm text-slate-200 leading-relaxed',
  userBubble: 'bg-gradient-to-r from-cyan-500 to-blue-600 text-white',
  assistantBubble: 'bg-slate-950/80 border border-white/10 text-slate-100 shadow-lg shadow-slate-950/35',
  attachmentButton: 'mt-3 flex items-center gap-2 px-3 py-2 bg-cyan-500/10 text-cyan-300 border border-cyan-400/20 rounded-lg hover:bg-cyan-500/15 transition-colors text-xs font-medium',
  assistantTimestamp: 'text-white/45',
  loadingBubble: 'bg-slate-950/80 rounded-2xl px-5 py-4 shadow-lg border border-white/10',
  loadingText: 'text-sm text-white/55',
  inputShell: 'bg-white/10 backdrop-blur-md border-t border-white/10 p-4',
  streamLabel: 'text-xs text-white/55',
  streamButtonActive: 'bg-cyan-500 text-white shadow-lg shadow-cyan-950/30',
  streamButtonIdle: 'bg-slate-900/80 border border-white/10 text-slate-300 hover:bg-slate-800 transition-colors',
  textarea: 'w-full px-4 py-3 pr-12 bg-slate-950/80 border border-white/10 rounded-xl resize-none focus:outline-none focus:ring-2 focus:ring-cyan-400/40 text-white placeholder:text-white/35',
  primaryButton: 'px-6 py-3 bg-gradient-to-r from-cyan-500 to-blue-600 text-white rounded-xl font-medium flex items-center gap-2 hover:from-cyan-600 hover:to-blue-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-lg shadow-cyan-950/25',
  downloadButton: 'px-4 py-2 bg-gradient-to-r from-cyan-500 to-blue-600 text-white rounded-lg text-sm font-medium flex items-center gap-2 hover:from-cyan-600 hover:to-blue-700 transition-all',
  clearButton: 'p-2 text-white/60 hover:text-red-400 transition-colors',
  backButton: 'p-2 text-white/60 hover:text-white transition-colors',
} as const;
